apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mysp
  name: mysp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: mysp
    spec:
      containers:
      - image: houcemserver/sp
        name: mysp
        ports:
        - name: mysp
          containerPort: 2222    
          
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mysp
  name: mysp
spec:
  type: NodePort
  ports:
    - port: 2222
      targetPort: 2222
  selector:
    name: mysp

